name: 'Android Debug Build'
description: 'Build Android application in debug mode'

inputs:
  package_name:
    description: 'Name of the Android project module'
    type: string
    required: true

runs:
  using: "composite"
  steps:
    # Check out repository code
    - name: Checkout
      uses: actions/checkout@v4

    # Setup Java development environment
    - name: Set up JDK 17
      uses: actions/setup-java@v4.2.2
      with:
        distribution: 'temurin'
        java-version: '17'

    # Configure Gradle build tool
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    # Cache Gradle dependencies to speed up builds
    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.konan
          build
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

    # Build signed release APK
    - name: Build Release
      env:
        KEYSTORE_PASSWORD: ${{ secrets.ORIGINAL_KEYSTORE_FILE_PASSWORD }}
        KEYSTORE_ALIAS: ${{ secrets.ORIGINAL_KEYSTORE_ALIAS }}
        KEYSTORE_ALIAS_PASSWORD: ${{ secrets.ORIGINAL_KEYSTORE_ALIAS_PASSWORD }}
        VERSION_CODE: ${{ steps.rel_number.outputs.version-code }}
      run: |
        ./gradlew :${{ inputs.package_name }}:assembleDemoDebug

    # Save built APKs as artifacts
    - name: Upload Android Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-debug-app
        retention-days: 1
        compression-level: 9
        path: './${{ inputs.package_name }}/build/outputs/apk/**/*.apk'



