# GitHub Actions Workflow for Play Store Release Promotion
#
# PURPOSE:
# This workflow automates the process of promoting a beta release
# to the production track on Google Play Store.
#
# PREREQUISITES:
# 1. Fastlane setup with Android deployment configurations
# 2. Configured Fastlane lanes:
#    - `promote_to_production`: Handles beta to production promotion
#
# REQUIRED CONFIGURATION:
# - Secrets:
#   PLAYSTORECREDS: Google Play Store service account JSON credentials
#
# INPUTS:
# - android_package_name: Name of the Android project module
#   (REQUIRED, must match your project's module structure)
#
# WORKFLOW TRIGGERS:
# - Can be called manually or triggered by other workflows
# - Typically used after beta testing and validation
#
# DEPLOYMENT PROCESS:
# 1. Checks out repository code
# 2. Sets up Ruby and Fastlane environment
# 3. Inflates Play Store credentials
# 4. Runs Fastlane lane to promote beta to production
#
# IMPORTANT NOTES:
# - Requires proper Fastlane configuration in your project
# - Ensures consistent and automated Play Store deployments
# - Configurable retry mechanism for upload stability
#
# RECOMMENDED FASTLANE LANE IMPLEMENTATION:
# ```ruby
# lane :promote_to_production do
#   upload_to_play_store(
#     track: 'beta',
#     track_promote_to: 'production',
#     json_key: './playStorePublishServiceCredentialsFile.json'
#   )
# end
# ```
### Example Workflow
#  ```yaml
# name: Promote Release to Play Store
#
# Workflow triggers:
# 1. Manual trigger with option to publish to Play Store
# 2. Automatic trigger when a GitHub release is published
# on:
#   workflow_dispatch:
#     inputs:
#       publish_to_play_store:
#         required: false
#         default: false
#         description: Publish to Play Store?
#         type: boolean
#   release:
#     types: [ released ]
#
# concurrency:
#   group: "production-deploy"
#   cancel-in-progress: false
#
# permissions:
#   contents: write
#
# jobs:
#   # Job to promote app from beta to production in Play Store
#   play_promote_production:
#     name: Promote Beta to Production Play Store
#     uses: openMF/mifos-mobile-github-actions/.github/workflows/promote-to-production.yaml@main
#     if: ${{ inputs.publish_to_play_store == true }}
#     secrets: inherit
#     with:
#       android_package_name: 'mifospay-android'
#   ```
#
# GitHub Actions workflow for deploying the app to production environments
# This workflow handles the promotion of beta releases to production on the Play Store
name: Promote Release to Play Store

on:
  workflow_call:
    inputs:
      android_package_name:
        description: 'Name of the Android project module'
        type: string
        required: true

# Environment variables
env:
  # Maximum number of retries for Play Store upload attempts
  SUPPLY_UPLOAD_MAX_RETRIES: 5

permissions:
  contents: write

jobs:
  # Job to promote app from beta to production in Play Store
  play_promote_production:
    name: Play Publish Production
    runs-on: macos-latest
    steps:
      # Check out repository code
      - uses: actions/checkout@v4

      # Set up Ruby environment for Fastlane
      - name: Configure Ruby
        uses: ruby/setup-ruby@a2bbe5b1b236842c1cb7dd11e8e3b51e0a616acc # v1.202.0
        with:
          bundler-cache: true

      # Install Fastlane and required plugins for deployment automation
      - name: Install Fastlane
        run: |
          gem install bundler:2.2.27
          bundle install --jobs 4 --retry 3
          bundle exec fastlane add_plugin firebase_app_distribution
          bundle exec fastlane add_plugin increment_build_number

      - name: Inflate Secrets
        shell: bash
        env:
          PLAYSTORE_CREDS: ${{ secrets.PLAYSTORECREDS }}
        run: |
          # Inflate PlayStore credentials
          touch ${{ inputs.android_package_name }}/playStorePublishServiceCredentialsFile.json
          echo $PLAYSTORE_CREDS > ${{ inputs.android_package_name }}/playStorePublishServiceCredentialsFile.json

      # Use Fastlane to promote the beta version to production
      - name: Promote Beta to Production Play Store
        run: |
          bundle exec fastlane android promote_to_production
